project:
  name: SmartContracts
  sourceFiles:
    - contracts/account-abstraction/SmartWallet.sol
spec:
  files: [certora/specs/SmartWallet.spec]
settings:
  maxBound: 10
  maxLoopBound: 100
  optimizationTimeout: 600
